// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, created_at, updated_at, email,hashed_pswd)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, created_at, updated_at, email, hashed_pswd, is_chirpy_red
`

type CreateUserParams struct {
	ID         uuid.UUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
	Email      string
	HashedPswd string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Email,
		arg.HashedPswd,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPswd,
		&i.IsChirpyRed,
	)
	return i, err
}

const getHashedPswd = `-- name: GetHashedPswd :one
select id, created_at, updated_at, email, hashed_pswd, is_chirpy_red from users where email=$1
`

func (q *Queries) GetHashedPswd(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getHashedPswd, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPswd,
		&i.IsChirpyRed,
	)
	return i, err
}

const reset = `-- name: Reset :exec
delete from users
`

func (q *Queries) Reset(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, reset)
	return err
}

const updateEmail = `-- name: UpdateEmail :exec
update users set email=$1,hashed_pswd=$2,updated_at=$3
where id =$4
`

type UpdateEmailParams struct {
	Email      string
	HashedPswd string
	UpdatedAt  time.Time
	ID         uuid.UUID
}

func (q *Queries) UpdateEmail(ctx context.Context, arg UpdateEmailParams) error {
	_, err := q.db.ExecContext(ctx, updateEmail,
		arg.Email,
		arg.HashedPswd,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const upgradeMembership = `-- name: UpgradeMembership :exec
update users set is_chirpy_red=true WHERE id=$1
`

func (q *Queries) UpgradeMembership(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, upgradeMembership, id)
	return err
}
